using RichDomainModel.Infrastructure.Configurations.Seedwork;
using RichDomainModel.Rich.Aggregates.TimeEntry;

namespace RichDomainModel.Infrastructure.Configurations.TimeEntry;

internal sealed class TimeEntryDescriptionConfiguration : StringValueObjectConfiguration<TimeEntryDescription>;